---
# file: define_etc_hosts.yaml - inventory variables build a standard /etc/hosts

- name: add local IP to DNS hostname in /etc/hosts
  shell:  LINE="{{ ansible_eth0.ipv4.address }}    {{ inventory_hostname }}"; FILE="/etc/hosts"; grep -qF -- "$LINE" "$FILE" || echo "$LINE" >> "$FILE"
  
