- name: create remote condor_poller directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
  - /opt/cloudscheduler/repository
  - /tmp/gentgz/cloudscheduler/data_collectors/condor
  - /tmp/gentgz/cloudscheduler/etc/cloudscheduler
  - /tmp/gentgz/cloudscheduler/etc/init.d
  - /tmp/gentgz/cloudscheduler/etc/systemd/system
  - /tmp/gentgz/cloudscheduler/lib
  - /tmp/gentgz/cloudscheduler/utilities

- stat:
    path: /tmp/gentgz/cloudscheduler/data_collectors/condor/cloudscheduler
  register: sym

- name: create cloudscheduler library link
  command:
    cmd: "ln -s ../../../cloudscheduler/ cloudscheduler"
    chdir: /tmp/gentgz/cloudscheduler/data_collectors/condor
  when: sym.stat.islnk is not defined

- name: copy remote condor_poller files
  copy:
    remote_src: yes
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
  - {src: /opt/cloudscheduler/data_collectors/condor/condor_poller.py,                    dest: /tmp/gentgz/cloudscheduler/data_collectors/condor/condor_poller.py}
  - {src: /opt/cloudscheduler/etc/cloudscheduler/condor_poller_README.md,                 dest: /tmp/gentgz/cloudscheduler/etc/cloudscheduler/condor_poller_README.md}
  - {src: /opt/cloudscheduler/etc/init.d/csv2-condor-poller.aremotefile,                  dest: /tmp/gentgz/cloudscheduler/etc/init.d/csv2-condor-poller.afile}
  - {src: /opt/cloudscheduler/etc/systemd/system/csv2-condor-poller.service.aremotefile,  dest: /tmp/gentgz/cloudscheduler/etc/systemd/system/csv2-condor-poller.service.afile}
  - {src: /opt/cloudscheduler/lib/attribute_mapper.py,                                    dest: /tmp/gentgz/cloudscheduler/lib/attribute_mapper.py}
  - {src: /opt/cloudscheduler/lib/db_config.py,                                           dest: /tmp/gentgz/cloudscheduler/lib/db_config.py}
  - {src: /opt/cloudscheduler/lib/fw_config.py,                                           dest: /tmp/gentgz/cloudscheduler/lib/fw_config.py}
  - {src: /opt/cloudscheduler/lib/poller_functions.py,                                    dest: /tmp/gentgz/cloudscheduler/lib/poller_functions.py}
  - {src: /opt/cloudscheduler/lib/ProcessMonitor.py,                                      dest: /tmp/gentgz/cloudscheduler/lib/ProcessMonitor.py}
  - {src: /opt/cloudscheduler/lib/log_tools.py,                                           dest: /tmp/gentgz/cloudscheduler/lib/log_tools.py}
  - {src: /opt/cloudscheduler/lib/schema.py,                                              dest: /tmp/gentgz/cloudscheduler/lib/schema.py}
  - {src: /opt/cloudscheduler/utilities/remote_condor_poller_README.md,                   dest: /tmp/gentgz/cloudscheduler/utilities/remote_condor_poller_README.md}

- name: copy remote condor_poller installation utility
  copy:
    remote_src: yes
    src: /opt/cloudscheduler/utilities/remote_condor_poller_enable
    dest: /tmp/gentgz/cloudscheduler/utilities/remote_condor_poller_enable
    owner: root
    group: root
    mode: 0744

- name: generate remote condor_poller support files
  template:
    src: "/tmp/cloudscheduler/{{ ansible_facts.fqdn }}/opt/cloudscheduler/etc/cloudscheduler/condor_poller.yaml.j2"
    dest: /tmp/gentgz/cloudscheduler/etc/cloudscheduler/condor_poller.yaml

- name: build the condor_poller tarball
  command:
    cmd: "tar -czvf /opt/cloudscheduler/repository/remote_condor_poller.tar.gz cloudscheduler"
    chdir: /tmp/gentgz

- name: remove the temporary condor_poller gentgz directory
  file:
    path: /tmp/gentgz
    state: absent

