---
# InfluxDb 

- name: Remove python-requests from yum install
  yum:
    name: python-requests
    state: absent

- name: Install InfluxDB python package.
  pip:
    name: influxdb

- name: Add InfluxDB `repository
  yum_repository:
    name: influxdb-repo
    description: InfluxDB YUM repo
    baseurl: https://repos.influxdata.com/rhel/$releasever/$basearch/stable
    gpgcheck: no

- name: install InfluxDB
  yum:
    name: ['influxdb']
    state: latest

- name: Start service InfluxDB
  service:
    name: influxdb
    state: started

- name: Wait for InfluxDB to be ready
  wait_for:
    port: 8086

- name: install cloud-init (removed with python-requests)
  yum:
    name: cloud-init
    state: present


- name: Create database
  influxdb_database:
      database_name: "csv2_timeseries"
      udp_port: 4444
