---

- hosts: csv2
  vars:
    ansible_bender:
        base_image: docker.io/centos/systemd
        layering: False
        ansible_extra_args: "-e addenda=addenda -u root"

        target_image:
          name: csv2-container:newerVersion 
          ports: [0-65000]
          entrypoint: '["/init.sh"]'
          cmd: "/usr/sbin/init"

  roles:
  - csv2

